import type { Metadata } from 'next';
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';
import './globals.css';
import { cn } from '@/utils/classNames';
import Providers from './Providers';

export const metadata: Metadata = {
  title: 'Component Library',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body
        className={cn(
          GeistMono.variable,
          GeistSans.variable,
          'relative bg-gray-100 font-sans dark:bg-neutral-900 dark:text-white'
        )}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
